name: keystore-frontend CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: docker.io
  IMAGE_NAME: keystore-frontend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  trigger:
    runs-on: ubuntu-latest
    needs: build

    steps:
#      - name: trigger deploy
#        run: |
#          curl -X POST \
#            -H "Authorization: token ${{ secrets.PAT }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            "https://api.github.com/repos/DevOps-Lab-Team/keystore-devops/dispatches" \
#            -d '{"event_type": "trigger_workflow"}'
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: DevOps-Lab-Team/keystore-devops
          event-type: trigger_workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

